# Generated by Django 6.0.5 on 2026-05-05 17:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_user_org_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=250, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('preparation_instructions', models.TextField(blank=True, verbose_name='instrucciones de preparación')),
                ('yield_quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='cantidad producida')),
                ('tracks_batch', models.BooleanField(default=True, verbose_name='control por lote')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Reactivo',
                'verbose_name_plural': 'Reactivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=80, verbose_name='número de lote')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='cantidad a producir')),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('in_progress', 'En proceso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='planned', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organización')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='lab_inventory.reagent', verbose_name='reactivo')),
            ],
            options={
                'verbose_name': 'Orden de producción',
                'verbose_name_plural': 'Órdenes de producción',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('rif', models.CharField(blank=True, max_length=20, verbose_name='RIF')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='persona de contacto')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=250, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('stock_min', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='stock mínimo')),
                ('stock_max', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='stock máximo')),
                ('tracks_batch', models.BooleanField(default=False, help_text='Si este insumo requiere trazabilidad por número de lote', verbose_name='control por lote')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='lab_inventory.category', verbose_name='categoría')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida'), ('adjustment', 'Ajuste')], max_length=15, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='cantidad')),
                ('batch_number', models.CharField(blank=True, max_length=80, verbose_name='número de lote')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organización')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='lab_inventory.productionorder', verbose_name='orden de producción')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='lab_inventory.supplier', verbose_name='proveedor')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='lab_inventory.supply', verbose_name='insumo')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='abreviatura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supply',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='lab_inventory.unitofmeasure', verbose_name='unidad de medida'),
        ),
        migrations.CreateModel(
            name='ReagentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='cantidad requerida')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notas')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab_inventory.reagent', verbose_name='reactivo')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='lab_inventory.supply', verbose_name='insumo')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab_inventory.unitofmeasure', verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'Ítem de receta',
                'verbose_name_plural': 'Ítems de receta',
                'ordering': ['supply__name'],
            },
        ),
        migrations.AddField(
            model_name='reagent',
            name='yield_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagents', to='lab_inventory.unitofmeasure', verbose_name='unidad de rendimiento'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization', 'name'], name='lab_invento_organiz_f2fa6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_category_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['organization', 'batch_number'], name='lab_invento_organiz_5824f4_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['organization', 'status'], name='lab_invento_organiz_d3137c_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['organization', '-created_at'], name='lab_invento_organiz_2d07db_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['organization', 'name'], name='lab_invento_organiz_cade26_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'supply'], name='lab_invento_organiz_a10501_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'movement_type'], name='lab_invento_organiz_6f6307_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', '-created_at'], name='lab_invento_organiz_acf05a_idx'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['organization', 'name'], name='lab_invento_organiz_694127_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('organization', 'abbreviation'), name='unique_uom_abbr_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['organization', 'code'], name='lab_invento_organiz_39ddf3_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['organization', 'name'], name='lab_invento_organiz_109135_idx'),
        ),
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_supply_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='reagent',
            index=models.Index(fields=['organization', 'name'], name='lab_invento_organiz_7bafc0_idx'),
        ),
    ]
