# Generated by Django 6.0.5 on 2026-05-12 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_org_constraint'),
        ('lab_inventory', '0002_reagentitem_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=80, verbose_name='número de lote')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organización')),
                ('reagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='lab_inventory.reagent', verbose_name='reactivo')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_inventory.supplier', verbose_name='proveedor')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='lab_inventory.supply', verbose_name='insumo')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='lab_inventory.batch', verbose_name='lote'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['organization', 'batch_number'], name='lab_invento_organiz_0056e4_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['organization', 'expiration_date'], name='lab_invento_organiz_490c06_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reagent__isnull', True), ('supply__isnull', False)), models.Q(('reagent__isnull', False), ('supply__isnull', True)), _connector='OR'), name='batch_supply_xor_reagent'),
        ),
    ]
