# Generated by Django 6.0.5 on 2026-05-12 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_org_constraint'),
        ('lab_inventory', '0003_batch_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='stock_max',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='stock máximo'),
        ),
        migrations.AddField(
            model_name='reagent',
            name='stock_min',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='stock mínimo'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='lab_inventory.reagent', verbose_name='reactivo'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='lab_inventory.supply', verbose_name='insumo'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reagent__isnull', True), ('supply__isnull', False)), models.Q(('reagent__isnull', False), ('supply__isnull', True)), _connector='OR'), name='movement_supply_xor_reagent'),
        ),
    ]
