# Generated by Django 6.0.4 on 2026-04-17 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Vacío solo para superadmins', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.organization', verbose_name='organización'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'superadmin'), ('organization__isnull', False), _connector='OR'), name='user_org_required_for_non_superadmin', violation_error_message='Solo los superadmins pueden existir sin organización.'),
        ),
    ]
