# Generated by Django 6.0.5 on 2026-05-05 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_org_constraint'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'leida'], name='notificatio_user_id_227d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', '-created_at'], name='notificatio_organiz_f822ba_idx'),
        ),
    ]
